const ROPSTEN_ETH_FAUCET_TO_SEND = 1; // ETH amount
const ROPSTEN_ETH_REQUESTOR_SUFFICIENT_BALANCE = 1; // ETH amount
const ROPSTEN_ETH_FAUCET_SUFFICIENT_BALANCE = 0.01; // ETH amount

const ROPSTEN_MXC_FAUCET_TO_SEND = 1; // MXC ERC-20 amount

module.exports = {
  ROPSTEN_ETH_FAUCET_TO_SEND,
  ROPSTEN_ETH_REQUESTOR_SUFFICIENT_BALANCE,
  ROPSTEN_ETH_FAUCET_SUFFICIENT_BALANCE,
  ROPSTEN_MXC_FAUCET_TO_SEND,
};
