const BN = require('bn.js');

const ONE = new BN(new BN(10, 10).pow(new BN(18, 10)), 10);
// Ropsten ETH has 18 decimal places
// 1000000000000000000 wei is 1 ETH
const ONE_ETH = ONE;
const ROPSTEN_ETH_FAUCET_TO_SEND = ONE_ETH.div(new BN(1000, 10)); // 0.001 ETH amount
const ROPSTEN_ETH_REQUESTOR_SUFFICIENT_BALANCE = ONE_ETH; // 1 ETH amount
const ROPSTEN_ETH_FAUCET_SUFFICIENT_BALANCE = ONE_ETH.div(new BN(100, 10)); // 0.01 ETH amount

// MXC ERC-20 token has 18 decimal places
// 1000000000000000000 is 1 MXC ERC-20 amount
const ONE_MXC = ONE;
const ROPSTEN_MXC_FAUCET_TO_SEND = ONE_MXC; // 1 MXC ERC-20 amount
const ROPSTEN_MXC_REQUESTOR_SUFFICIENT_BALANCE = ONE_MXC; // 1 MXC ERC-20 amount
const ROPSTEN_MXC_FAUCET_SUFFICIENT_BALANCE = ONE_MXC.div(new BN(100, 10)); // 0.01 MXC ERC-20 amount

module.exports = {
  ROPSTEN_ETH_FAUCET_TO_SEND,
  ROPSTEN_ETH_REQUESTOR_SUFFICIENT_BALANCE,
  ROPSTEN_ETH_FAUCET_SUFFICIENT_BALANCE,
  ROPSTEN_MXC_FAUCET_TO_SEND,
  ROPSTEN_MXC_REQUESTOR_SUFFICIENT_BALANCE,
  ROPSTEN_MXC_FAUCET_SUFFICIENT_BALANCE
};
